repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'
- repo: https://github.com/ambv/black
  rev: 18.6b4
  hooks:
    - id: black
      args: [--line-length=100, --safe]
      python_version: python3.6
      exclude: '^.*migrations.*$'
