SENTENCES = (
    'Took longer than I expected.',
    'Awesome product! Will buy this again.',
    'My son loves it.',
    'My daughter loves it.',
    'Exactly what I was looking for.',
    'Shipping was quite fast. I\'m really looking forward to trying this out :D',
    'It was a little bigger than I expected.',
    'Fitted perfectly.',
    'So fast.',
    'Wow!',
    'Sick.',
    'The screen size is just what I need.',
    'I like the colours.',
    'Not as large as I expected.',
    'The top is a lot brighter than in the pictures',
    'I didn\'nt even know movies could look this good!',
)
